#!/bin/bash

# remember: this is not run as the node user!
# remember: this gets run from /home/node/site-staging

OWD=`pwd`
cd /home/node/site-staging
STAGE_DIR=`pwd -P`
cd $OWD

sudo stop genassist-production
sudo rm /home/node/site-production
sudo ln -s $STAGE_DIR /home/node/site-production
ln -f -s ${STAGE_DIR} /home/node/site-production
sudo cp ${STAGE_DIR}/conf/nginx-production /etc/nginx/sites-available/genassist-production
sudo ln -f -s /etc/nginx/sites-available/genassist-production /etc/nginx/sites-enabled/genassist-production
sudo touch /var/log/genassist-production-node.log
sudo cp ${STAGE_DIR}/conf/upstart-genassist-production /etc/init/genassist-production.conf

# database
NODE_ENV=production sudo ${STAGE_DIR}/bin/setup_db

# chowning
sudo chown -R node:node ${STAGE_DIR}
sudo chown -R node:node /home/node/site-production
sudo chown node /var/log/genassist-production-node.log

# startup
sudo start genassist-production
sudo /etc/init.d/nginx restart

echo Successfully updated production
