#!/bin/bash

# remember: this is not run as the node user!
# remember: this gets run from /home/node/site-production
STAMP=`date '+%Y%m%d_%H%M%S'`

PROD_DB=`sudo -u node NODE_ENV=production -i /home/node/site-production/bin/db_info | grep Database\ location | awk '{print $3}'`
STAG_DB=`sudo -u node NODE_ENV=staging -i /home/node/site-production/bin/db_info | grep Database\ location | awk '{print $3}'`
sudo -u node cp $STAG_DB $STAG_DB.$STAMP
sudo -u node cp $PROD_DB $STAG_DB