#!/bin/bash

CMD=$1
if [ -z $2 ] ; then
  STAMP=`date '+%Y%m%d_%H%M%S'`
else
  STAMP=$2
fi

BUNDLE=site_${STAMP}.tgz
BUNDLE_PATH=dist/${BUNDLE}
SSHHOST=gdusbabek@genassist.tagfriendly.com

doArtifact(){
  mkdir -p dist
  git archive --format tar.gz --output ${BUNDLE_PATH} master
}

doStage() {
  if [ ! -a $BUNDLE_PATH ] ; then
    doArtifact
  fi
  scp ${BUNDLE_PATH} ${SSHHOST}:/home/gdusbabek/site_bundles/${BUNDLE}
  ssh ${SSHHOST} \'\'sudo cp /home/gdusbabek/site_bundles/${BUNDLE} /home/node/site_bundles/${BUNDLE}\'\'
  ssh ${SSHHOST} \'\'sudo chown node /home/node/site_bundles/${BUNDLE}\'\'
  ssh ${SSHHOST} \'\'sudo -u node mkdir -p /home/node/site_bundles/site_${STAMP}\'\'
  ssh ${SSHHOST} \'\'sudo -u node tar -C /home/node/site_bundles/site_${STAMP} -xzf /home/node/site_bundles/${BUNDLE}\'\'
  ssh ${SSHHOST} \'\'sudo /home/node/site_bundles/site_${STAMP}/dev-bin/update_staging\'\'
}

doPromote() {
  echo promoting site_${STAMP}
  ssh ${SSHHOST} \'\'sudo /home/node/site_bundles/site_${STAMP}/dev-bin/promote_staging\'\'
}

doClean() {
  echo foo
}

doReplaceDb() {
  ssh ${SSHHOST} \'\'sudo /home/node/site-production/dev-bin/replace_stage_db\'\'
}

case "$CMD" in

artifact) doArtifact
          ;;
stage)    doStage
          ;;
promote)  doPromote
          ;;
clean)    doClean
          ;;
*)        echo nothing to do
          ;;
esac

exit $?